export const FIXTURE_IDS = Object.freeze({
  staff: Object.freeze({
    admin: 'staff:demo-admin',
    frontDesk: 'staff:demo-front-desk',
    coach: 'staff:demo-coach',
    multiRole: 'staff:demo-front-desk-coach',
    inactive: 'staff:demo-inactive',
  } as const),
  members: Object.freeze({
    maple: 'member:maple',
    cedar: 'member:cedar',
    birch: 'member:birch',
    willow: 'member:willow',
    aspen: 'member:aspen',
    juniper: 'member:juniper',
    fern: 'member:fern',
    moss: 'member:moss',
  } as const),
  invitations: Object.freeze({
    maple: 'invitation:maple',
    cedar: 'invitation:cedar',
    birch: 'invitation:birch',
    willow: 'invitation:willow',
    aspen: 'invitation:aspen',
    juniper: 'invitation:juniper',
    fern: 'invitation:fern',
    moss: 'invitation:moss',
    outstanding: 'invitation:demo-outstanding',
    expired: 'invitation:demo-expired',
    revoked: 'invitation:demo-revoked',
    superseded: 'invitation:demo-superseded',
    replacement: 'invitation:demo-replacement',
  } as const),
  waivers: Object.freeze({
    old: 'waiver:demo-old',
    current: 'waiver:demo-current',
    draft: 'waiver:demo-draft',
  } as const),
  signatures: Object.freeze({
    mapleOld: 'signature:maple-old',
    cedarOld: 'signature:cedar-old',
    birchOld: 'signature:birch-old',
    willowOld: 'signature:willow-old',
    aspenOld: 'signature:aspen-old',
    juniperOld: 'signature:juniper-old',
    mossOld: 'signature:moss-old',
    mapleCurrent: 'signature:maple-current',
    cedarCurrent: 'signature:cedar-current',
    birchCurrent: 'signature:birch-current',
    willowCurrent: 'signature:willow-current',
    juniperCurrent: 'signature:juniper-current',
    fernCurrent: 'signature:fern-current',
    mossCurrent: 'signature:moss-current',
  } as const),
  stations: Object.freeze({
    north: 'station:demo-north',
    west: 'station:demo-west',
    east: 'station:demo-east',
    outage: 'station:demo-outage',
  } as const),
  classTypes: Object.freeze({
    sprint: 'classType:demo-sprint',
    technique: 'classType:demo-technique',
    endurance: 'classType:demo-endurance',
  } as const),
  templates: Object.freeze({
    weekA: 'template:demo-week-a',
    weekB: 'template:demo-week-b',
  } as const),
  templateEntries: Object.freeze({
    monday: 'templateEntry:week-a-monday',
    wednesday: 'templateEntry:week-a-wednesday',
    tuesday: 'templateEntry:week-b-tuesday',
    thursday: 'templateEntry:week-b-thursday',
  } as const),
  classes: Object.freeze({
    history: 'class:demo-history',
    cancelled: 'class:demo-cancelled',
    checkIn: 'class:demo-check-in',
    free: 'class:demo-free',
    full: 'class:demo-full',
    draft: 'class:demo-draft',
    laterRelease: 'class:demo-later-release',
  } as const),
  bookings: Object.freeze({
    historyAttended: 'booking:history-attended',
    historyNoShow: 'booking:history-no-show',
    historyCorrected: 'booking:history-corrected',
    historyLateCancel: 'booking:history-late-cancel',
    historyRemoved: 'booking:history-removed',
    cancelled: 'booking:cancelled-class',
    cancelledCedar: 'booking:cancelled-class-cedar',
    cancelledBirch: 'booking:cancelled-class-birch',
    checkInMaple: 'booking:check-in-maple',
    checkInCedar: 'booking:check-in-cedar',
    outage: 'booking:outage-moss',
    outdatedWaiver: 'booking:free-aspen',
    fullMaple: 'booking:full-maple',
    fullCedar: 'booking:full-cedar',
    fullBirch: 'booking:full-birch',
    fullPrevious: 'booking:full-previous-juniper',
  } as const),
  waitlist: Object.freeze({
    birchPromoted: 'waitlist:full-birch-promoted',
    moss: 'waitlist:full-moss',
    aspen: 'waitlist:full-aspen',
    willow: 'waitlist:full-willow',
    juniperLeft: 'waitlist:full-juniper-left',
    cancelled: 'waitlist:cancelled-willow',
  } as const),
  attendance: Object.freeze({
    historyAttended: 'attendance:history-attended',
    historyNoShow: 'attendance:history-no-show',
    historyCorrected: 'attendance:history-corrected',
    historyLateCancel: 'attendance:history-late-cancel',
    historyRemoved: 'attendance:history-removed',
    cancelled: 'attendance:cancelled-class',
    cancelledCedar: 'attendance:cancelled-class-cedar',
    cancelledBirch: 'attendance:cancelled-class-birch',
    checkInMaple: 'attendance:check-in-maple',
    checkInCedar: 'attendance:check-in-cedar',
    outage: 'attendance:outage-moss',
    outdatedWaiver: 'attendance:free-aspen',
    fullMaple: 'attendance:full-maple',
    fullCedar: 'attendance:full-cedar',
    fullBirch: 'attendance:full-birch',
    fullPrevious: 'attendance:full-previous-juniper',
  } as const),
  corrections: Object.freeze({
    historyReconciled: 'correction:history-reconciled',
  } as const),
  notifications: Object.freeze({
    invitationFailed: 'notification:demo-invitation-failed',
    bookingConfirmed: 'notification:demo-booking-confirmed',
    waitlistPromoted: 'notification:demo-waitlist-promoted',
    classCancelled: 'notification:demo-class-cancelled',
    classChanged: 'notification:demo-class-changed',
  } as const),
  scenarios: Object.freeze({
    baseline: 'scenario:baseline',
  } as const),
  clockPresets: Object.freeze({
    baseline: 'clockPreset:baseline',
    checkInOpens: 'clockPreset:check-in-opens',
    classStart: 'clockPreset:class-start',
    checkInCloses: 'clockPreset:check-in-closes',
    classEnd: 'clockPreset:class-end',
    fullLateCancelCutoff: 'clockPreset:full-late-cancel-cutoff',
    fullWaitlistCutoff: 'clockPreset:full-waitlist-cutoff',
  } as const),
});
